package com.uong.phormi

import android.content.Context
import android.graphics.BitmapFactory
import android.graphics.Color
import android.graphics.drawable.GradientDrawable
import android.text.InputType
import android.view.Gravity
import android.view.View
import android.view.ViewGroup
import android.view.inputmethod.EditorInfo
import android.widget.Button
import android.widget.FrameLayout
import android.widget.HorizontalScrollView
import android.widget.ImageView
import android.widget.LinearLayout
import android.widget.ScrollView
import android.widget.TextView
import java.io.File
import java.util.WeakHashMap

/** One bounded Phormi IME surface: tools replace the content, never the app. */
internal object PhormiKeyboardUi {
 private var density=1f
 private val lastContext=WeakHashMap<PhormiKeyboardServiceV2,String>()
 fun render(s:PhormiKeyboardServiceV2):View{density=s.resources.displayMetrics.density;return when(panel(s)){"EMOJI"->emoji(s);"CLIPBOARD"->clipboard(s);"AI_EMOJI"->aiEmoji(s);else->keyboard(s)}}
 private fun base(s:PhormiKeyboardServiceV2)=LinearLayout(s).apply{orientation=LinearLayout.VERTICAL;setPadding(d(s,6),d(s,5),d(s,6),d(s,5));setBackgroundColor(Color.rgb(13,18,30))}
 private fun hscroll(s:PhormiKeyboardServiceV2)=HorizontalScrollView(s).apply{isHorizontalScrollBarEnabled=false;addView(LinearLayout(s).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL})}
 private fun b(s:PhormiKeyboardServiceV2,label:String,action:()->Unit)=Button(s).apply{text=label;textSize=if(label.length==1)20f else 13f;setTextColor(Color.WHITE);typeface=if(label.length>1)android.graphics.Typeface.DEFAULT_BOLD else android.graphics.Typeface.DEFAULT;minWidth=0;minHeight=0;isAllCaps=false;stateListAnimator=null;setPadding(d(s,3),0,d(s,3),0);background=bg(Color.rgb(39,48,64),10);contentDescription=label;setOnClickListener{action()}}
 private fun tx(s:PhormiKeyboardServiceV2,t:String,size:Float=14f,bold:Boolean=false)=TextView(s).apply{text=t;textSize=size;setTextColor(Color.rgb(203,213,225));gravity=Gravity.CENTER_VERTICAL;typeface=if(bold)android.graphics.Typeface.DEFAULT_BOLD else android.graphics.Typeface.DEFAULT;maxLines=3}
 private fun add(s:PhormiKeyboardServiceV2,row:LinearLayout,label:String,weight:Float=1f,action:()->Unit){row.addView(b(s,label,action),lp(0,50,weight))}
 private fun keyboard(s:PhormiKeyboardServiceV2):View{
  val root=base(s);val bar=hscroll(s);val r=bar.getChildAt(0) as LinearLayout
  r.addView(b(s,"▦"){tools(s)},lp(52,42));r.addView(b(s,"😀"){setPanel(s,"EMOJI");renderTo(s)},lp(52,42));r.addView(b(s,"📋"){setPanel(s,"CLIPBOARD");renderTo(s)},lp(52,42));r.addView(b(s,"GIF"){media(s,"GIF")},lp(58,42));r.addView(b(s,"Sticker"){media(s,"Sticker")},lp(76,42));if(s.shouldOfferSwitchingToNextInputMethod())r.addView(b(s,"🌐"){runCatching{s.switchToNextInputMethod(false)}},lp(52,42));root.addView(bar,lp(-1,46))
  val info=info(s);if(info!=null&&!privateField(info)){val context=PhormiKeyboardTextEngine.contextBeforeCursor(s.currentInputConnection);if(context.isNotBlank()&&aiOn(s)&&context!=lastContext[s]){lastContext[s]=context;invoke(s,"prepareAiContext")}}
  val sr=LinearLayout(s).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL};val ai=if(aiOn(s))aiFiles(s).firstOrNull() else null;val mood=if(info!=null&&!privateField(info)&&aiOn(s))PhormiKeyboardAiContext.suggestions(PhormiKeyboardTextEngine.contextBeforeCursor(s.currentInputConnection)).firstOrNull() else null;val sug=suggestions(s)
  val views=mutableListOf<View>();if(ai!=null)views+=img(s,ai);if(mood!=null)views+=b(s,mood.emoji){commit(s,mood.emoji)};sug.take((3-views.size).coerceAtLeast(0)).forEach{v->views+=b(s,v){commit(s,v+" ")}};views.take(3).forEach{sr.addView(it,lp(0,42,1f).apply{setMargins(d(s,2),d(s,1),d(s,2),d(s,1))})};if(sr.childCount>0)root.addView(sr,lp(-1,46))
  val type=info?.inputType?:InputType.TYPE_CLASS_TEXT;val clazz=type and InputType.TYPE_MASK_CLASS;val varr=type and InputType.TYPE_MASK_VARIATION;val number=clazz==InputType.TYPE_CLASS_NUMBER;val phone=clazz==InputType.TYPE_CLASS_PHONE;val date=clazz==InputType.TYPE_CLASS_DATETIME;val email=varr==InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS||varr==InputType.TYPE_TEXT_VARIATION_WEB_EMAIL_ADDRESS;val uri=varr==InputType.TYPE_TEXT_VARIATION_URI;val symbols=bool(s,"symbols")
  val rows=when{phone->listOf("1234567890","*#+-","().");number->listOf("1234567890","789456123","0.,+-");date->listOf("1234567890","4567891230",":/-");symbols->listOf("1234567890","-=[]\\;',./","!@#\$%^&*()","_+{}|:\"<>?");else->listOf("qwertyuiop","asdfghjkl","zxcvbnm")};rows.forEach{chars->val row=LinearLayout(s).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER};val upper=bool(s,"shift")||bool(s,"capsLock");chars.forEach{c->val label=if(upper&&c.isLetter())c.uppercaseChar().toString()else c.toString();add(s,row,label){commit(s,label);if(bool(s,"shift")&&!bool(s,"capsLock"))setBool(s,"shift",false);renderTo(s)}};root.addView(row,lp(-1,54))}
  if(email||uri){val row=LinearLayout(s).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER};(if(email)listOf("@",".com",".net",".org")else listOf("/",".com","https://",".org")).forEach{v->add(s,row,v){commit(s,v)}};root.addView(row,lp(-1,54))}
  val bottom=LinearLayout(s).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER};if(!number&&!phone&&!date){add(s,bottom,if(symbols)"ABC"else"123",.8f){setBool(s,"symbols",!symbols);renderTo(s)};add(s,bottom,if(bool(s,"capsLock"))"⇧·"else"⇧",.8f){invoke(s,"toggleShift");renderTo(s)};add(s,bottom,"Sel",.8f){invoke(s,"selectAll")};add(s,bottom,"Copy",.8f){invoke(s,"copySelection")};add(s,bottom,"Paste",.8f){invoke(s,"pasteClipboard");renderTo(s)}};add(s,bottom,"Space",2.5f){commit(s," ")};add(s,bottom,"←",.8f){move(s,-1)};add(s,bottom,"→",.8f){move(s,1)};add(s,bottom,"⌫",.9f){delete(s)};add(s,bottom,action(info),1f){invoke(s,"sendEditorAction")};if(!number&&!phone&&!date)add(s,bottom,"🎙",.9f){PhormiKeyboardVoiceController.listen(s){commit(s,it)}};root.addView(bottom,lp(-1,58));return root
 }
 private fun emoji(s:PhormiKeyboardServiceV2):View{val root=base(s);val nav=hscroll(s);val r=nav.getChildAt(0)as LinearLayout;r.addView(b(s,"ABC"){setPanel(s,"KEYBOARD");renderTo(s)},lp(58,42));PhormiKeyboardEmoji.categories.keys.forEachIndexed{i,k->r.addView(b(s,k){setInt(s,"emojiCategory",i);renderTo(s)},lp(48,42))};r.addView(b(s,"⚙"){settings(s)},lp(48,42));root.addView(nav,lp(-1,46));val context=PhormiKeyboardTextEngine.contextBeforeCursor(s.currentInputConnection);val reaction=LinearLayout(s).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER};if(context.isNotBlank()&&!privateField(info(s))){PhormiKeyboardAiContext.suggestions(context).firstOrNull()?.let{m->add(s,reaction,m.emoji){commit(s,m.emoji)}};if(aiOn(s))aiFiles(s).firstOrNull()?.let{add(s,reaction," "){commitContent(s,it)}}};if(reaction.childCount>0)root.addView(reaction,lp(-1,52));val scroll=ScrollView(s);val grid=LinearLayout(s).apply{orientation=LinearLayout.VERTICAL};val vals=PhormiKeyboardEmoji.categories.values.elementAtOrNull(int(s,"emojiCategory")).orEmpty();vals.chunked(8).forEach{g->val row=LinearLayout(s).apply{orientation=LinearLayout.HORIZONTAL};g.forEach{e->add(s,row,e){commit(s,e)}};while(row.childCount<8)row.addView(View(s),lp(0,50,1f));grid.addView(row,lp(-1,54))};scroll.addView(grid);root.addView(scroll,lp(-1,0,1f));return root}
 private fun clipboard(s:PhormiKeyboardServiceV2):View{val root=base(s);val head=LinearLayout(s).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER};head.addView(b(s,"←"){setPanel(s,"KEYBOARD");renderTo(s)});head.addView(tx(s,"Clipboard",17f,true),lp(0,46,1f));head.addView(b(s,"Clear"){PhormiKeyboardClipboardStore.clearUnpinned(s);renderTo(s)});root.addView(head,lp(-1,50));val scroll=ScrollView(s);val list=LinearLayout(s).apply{orientation=LinearLayout.VERTICAL};PhormiKeyboardClipboardStore.list(s).forEach{item->val row=LinearLayout(s).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;background=bg(Color.rgb(30,41,59),12);setPadding(d(s,8),0,d(s,4),0)};row.addView(tx(s,item.text),lp(0,58,1f));row.addView(b(s,if(item.pinned)"📌"else"○"){PhormiKeyboardClipboardStore.togglePinned(s,item.text);renderTo(s)},lp(46,54));row.setOnClickListener{commit(s,item.text)};row.setOnLongClickListener{PhormiKeyboardClipboardStore.remove(s,item.text);renderTo(s);true};list.addView(row,lp(-1,64).apply{setMargins(0,d(s,3),0,d(s,3))})};if(list.childCount==0)list.addView(tx(s,"Copy something to build your local clipboard."),lp(-1,70));scroll.addView(list);root.addView(scroll,lp(-1,0,1f));return root}
 private fun aiEmoji(s:PhormiKeyboardServiceV2):View{val root=base(s);val head=LinearLayout(s).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER};head.addView(b(s,"←"){setPanel(s,"KEYBOARD");renderTo(s)});head.addView(tx(s,"AI Emoji",17f,true),lp(0,46,1f));head.addView(b(s,if(aiOn(s))"ON"else"OFF"){toggleAi(s);renderTo(s)});root.addView(head,lp(-1,50));val context=PhormiKeyboardTextEngine.contextBeforeCursor(s.currentInputConnection);root.addView(tx(s,if(context.isBlank())"Type to create a context reaction."else"Context: "+context.takeLast(70),12f),lp(-1,42));val scroll=ScrollView(s);val list=LinearLayout(s).apply{orientation=LinearLayout.VERTICAL};aiFiles(s).take(4).forEach{f->list.addView(img(s,f),lp(-1,60))};if(list.childCount==0)list.addView(tx(s,if(aiOn(s))"Generating…"else"AI emoji is off."),lp(-1,80));scroll.addView(list);root.addView(scroll,lp(-1,0,1f));return root}
 private fun tools(s:PhormiKeyboardServiceV2){val root=base(s);root.addView(tx(s,"Phormi tools",17f,true),lp(-1,46));val g=LinearLayout(s).apply{orientation=LinearLayout.VERTICAL};listOf("😀 Emoji" to{"${setPanel(s,"EMOJI")}"},"📋 Clipboard" to{"${setPanel(s,"CLIPBOARD")}"},"✨ AI Emoji" to{"${setPanel(s,"AI_EMOJI")}"},"⚙ Settings" to{"settings(s)"},"GIF" to{"media(s,"GIF")},"Sticker" to{"media(s,"Sticker")},"🎙 Voice" to{"PhormiKeyboardVoiceController.listen(s){commit(s,it)}}).chunked(2).forEach{pair->val row=LinearLayout(s).apply{orientation=LinearLayout.HORIZONTAL};pair.forEach{(label,action)->add(s,row,label){when(label){"⚙ Settings"->settings(s);"GIF"->media(s,"GIF");"Sticker"->media(s,"Sticker");"🎙 Voice"->PhormiKeyboardVoiceController.listen(s){commit(s,it)};else->{action();renderTo(s)}}}};g.addView(row,lp(-1,60))};root.addView(g,lp(-1,0,1f));s.setInputView(root)}
 private fun settings(s:PhormiKeyboardServiceV2){val root=base(s);val head=LinearLayout(s).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER};head.addView(b(s,"←"){setPanel(s,"KEYBOARD");renderTo(s)});head.addView(tx(s,"Phormi Keyboard",17f,true),lp(0,46,1f));root.addView(head,lp(-1,50));val list=LinearLayout(s).apply{orientation=LinearLayout.VERTICAL};setting(s,list,"Suggestions",PhormiKeyboardPreferences.KEY_SUGGESTIONS,PhormiKeyboardPreferences.suggestions(s));setting(s,list,"Autocorrect",PhormiKeyboardPreferences.KEY_AUTOCORRECT,PhormiKeyboardPreferences.autocorrect(s));setting(s,list,"Auto-capitalization",PhormiKeyboardPreferences.KEY_AUTO_CAPS,PhormiKeyboardPreferences.autoCaps(s));setting(s,list,"AI emoji",PhormiKeyboardPreferences.KEY_AI_EMOJI,aiOn(s));setting(s,list,"Haptic feedback",PhormiKeyboardPreferences.KEY_HAPTIC,PhormiKeyboardPreferences.haptic(s));setting(s,list,"Key sounds",PhormiKeyboardPreferences.KEY_SOUND,PhormiKeyboardPreferences.sound(s));val hr=LinearLayout(s).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER};hr.addView(tx(s,"Keyboard height",14f,true),lp(0,54,1f));add(s,hr,"−",.6f){PhormiKeyboardPreferences.setHeight(s,PhormiKeyboardPreferences.height(s)-1);renderTo(s)};hr.addView(tx(s,"${PhormiKeyboardPreferences.height(s)+1}/7",14f,true),lp(46,54));add(s,hr,"+",.6f){PhormiKeyboardPreferences.setHeight(s,PhormiKeyboardPreferences.height(s)+1);renderTo(s)};list.addView(hr,lp(-1,58));val scroll=ScrollView(s);scroll.addView(list);root.addView(scroll,lp(-1,0,1f));s.setInputView(root)}
 private fun setting(s:PhormiKeyboardServiceV2,list:LinearLayout,label:String,key:String,on:Boolean){val row=LinearLayout(s).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER};row.addView(tx(s,label,14f),lp(0,54,1f));add(s,row,if(on)"ON"else"OFF",.7f){PhormiKeyboardPreferences.set(s,key,!on);renderTo(s)};list.addView(row,lp(-1,58))}
 private fun media(s:PhormiKeyboardServiceV2,kind:String){val root=base(s);root.addView(tx(s,kind,17f,true),lp(-1,50));root.addView(tx(s,if(kind=="Sticker")"Stickers stay inside Phormi. Generated reactions are available here."else"GIFs stay inside Phormi. Recent generated media appears here."),lp(-1,70));aiFiles(s).take(6).forEach{root.addView(img(s,it),lp(84,84))};root.addView(b(s,"← Keyboard"){setPanel(s,"KEYBOARD");renderTo(s)},lp(-1,54));s.setInputView(root)}
 private fun img(s:PhormiKeyboardServiceV2,f:File):View=FrameLayout(s).apply{background=bg(Color.rgb(39,48,64),10);contentDescription="Phormi generated reaction";addView(ImageView(s).apply{setImageBitmap(BitmapFactory.decodeFile(f.absolutePath));scaleType=ImageView.ScaleType.CENTER_INSIDE;setPadding(d(s,5),d(s,5),d(s,5),d(s,5))},FrameLayout.LayoutParams(-1,-1));setOnClickListener{commitContent(s,f)}}
 private fun commitContent(s:PhormiKeyboardServiceV2,f:File){PhormiKeyboardServiceV2.commitPickedContent(s,PhormiKeyboardStickerStore.contentUri(s,f))}
 private fun commit(s:PhormiKeyboardServiceV2,t:String){s.currentInputConnection?.commitText(t,1);invokeRefresh(s);if(aiOn(s))invoke(s,"prepareAiContext");renderTo(s)}
 private fun delete(s:PhormiKeyboardServiceV2){s.currentInputConnection?.deleteSurroundingTextInCodePoints(1,0);invokeRefresh(s);renderTo(s)}
 private fun move(s:PhormiKeyboardServiceV2,delta:Int){s.currentInputConnection?.sendKeyEvent(android.view.KeyEvent(if(delta<0)android.view.KeyEvent.KEYCODE_DPAD_LEFT else android.view.KeyEvent.KEYCODE_DPAD_RIGHT));invokeRefresh(s);renderTo(s)}
 private fun toggleAi(s:PhormiKeyboardServiceV2){PhormiKeyboardPreferences.set(s,PhormiKeyboardPreferences.KEY_AI_EMOJI,!aiOn(s));if(!aiOn(s))invoke(s,"prepareAiContext")}
 private fun panel(s:PhormiKeyboardServiceV2)=field(s,"panel")?.toString().orEmpty()
 private fun setPanel(s:PhormiKeyboardServiceV2,name:String){runCatching{findField(s,"panel")?.let{it.isAccessible=true;it.set(s,it.type.enumConstants.first{v->v.toString()==name})}}}
 private fun info(s:PhormiKeyboardServiceV2):EditorInfo?=field(s,"editorInfo")as?EditorInfo
 private fun privateField(i:EditorInfo?)=i?.let{PhormiKeyboardTextEngine.isPassword(it)||PhormiKeyboardTextEngine.isUriLike(it)||PhormiKeyboardTextEngine.isNoPersonalizedLearning(it)}?:true
 private fun aiOn(s:Context)=PhormiKeyboardPreferences.aiEmoji(s)
 private fun aiFiles(s:PhormiKeyboardServiceV2)=runCatching{@Suppress("UNCHECKED_CAST")(field(s,"aiFiles")as?List<File>).orEmpty().filter{it.isFile&&it.length()>0}}.getOrDefault(emptyList())
 private fun suggestions(s:PhormiKeyboardServiceV2)=runCatching{@Suppress("UNCHECKED_CAST")(field(s,"lastSuggestions")as?List<String>).orEmpty().distinct()}.getOrDefault(emptyList())
 private fun bool(s:PhormiKeyboardServiceV2,n:String)=field(s,n)as?Boolean?:false
 private fun int(s:PhormiKeyboardServiceV2,n:String)=field(s,n)as?Int?:0
 private fun setBool(s:PhormiKeyboardServiceV2,n:String,v:Boolean){findField(s,n)?.let{it.isAccessible=true;it.setBoolean(s,v)}}
 private fun setInt(s:PhormiKeyboardServiceV2,n:String,v:Int){findField(s,n)?.let{it.isAccessible=true;it.setInt(s,v)}}
 private fun field(s:PhormiKeyboardServiceV2,n:String):Any?=runCatching{findField(s,n)?.apply{isAccessible=true}?.get(s)}.getOrNull()
 private fun findField(s:PhormiKeyboardServiceV2,n:String):java.lang.reflect.Field?{var c:Class<*>?=s.javaClass;while(c!=null){c.declaredFields.firstOrNull{it.name==n}?.let{return it};c=c.superclass};return null}
 private fun invoke(s:PhormiKeyboardServiceV2,n:String){runCatching{findMethod(s,n)?.apply{isAccessible=true}?.invoke(s)}}
 private fun invokeRefresh(s:PhormiKeyboardServiceV2){runCatching{findMethod(s,"refreshPredictions")?.let{it.isAccessible=true;if(it.parameterTypes.size==1)it.invoke(s,false)else it.invoke(s)}}}
 private fun findMethod(s:PhormiKeyboardServiceV2,n:String):java.lang.reflect.Method?{var c:Class<*>?=s.javaClass;while(c!=null){c.declaredMethods.firstOrNull{it.name==n&&it.parameterTypes.size<=1}?.let{return it};c=c.superclass};return null}
 private fun renderTo(s:PhormiKeyboardServiceV2){s.setInputView(render(s))}
 private fun action(i:EditorInfo?)=when(i?.imeOptions?.and(EditorInfo.IME_MASK_ACTION)){EditorInfo.IME_ACTION_GO->"Go";EditorInfo.IME_ACTION_SEARCH->"Search";EditorInfo.IME_ACTION_SEND->"Send";EditorInfo.IME_ACTION_NEXT->"Next";EditorInfo.IME_ACTION_DONE->"Done";else->"↵"}
 private fun bg(c:Int,r:Int)=GradientDrawable().apply{setColor(c);cornerRadius=r.toFloat()}
 private fun d(s:Context,v:Int)=(v*s.resources.displayMetrics.density).toInt().coerceAtLeast(1)
 private fun lp(w:Int,h:Int,weight:Float=0f)=LinearLayout.LayoutParams(if(w==-1||w==0)w else(w*density).toInt(),(h*density).toInt(),weight)
}
