package com.uong.phormi

import android.Manifest
import android.content.*
import android.content.pm.PackageManager
import android.graphics.*
import android.graphics.drawable.ColorDrawable
import android.inputmethodservice.InputMethodService
import android.net.Uri
import android.os.*
import android.speech.*
import android.text.InputType
import android.view.*
import android.view.inputmethod.*
import android.widget.*
import java.util.Locale
import kotlin.math.max
import kotlin.math.min

class PhormiKeyboardService : InputMethodService() {
    companion object { const val ACTION_COMMIT_TEXT="com.uong.phormi.keyboard.COMMIT_TEXT"; const val EXTRA_TEXT="text"; private var instance:PhormiKeyboardService?=null; fun commitPickedContent(context:Context,uri:Uri)=instance?.commitContent(uri)?:false }
    private enum class Panel { KEYBOARD, NUMBERS, SYMBOLS, EMOJI, CLIPBOARD, GIF, STICKER }
    private var shift=false; private var capsLock=false; private var panel=Panel.KEYBOARD; private var emojiCategory=0; private var editorInfo:EditorInfo?=null; private var selectionStart=0; private var selectionEnd=0; private var speech:SpeechRecognizer?=null; private var speechListening=false; private var aiJobToken=0; private var lastContext=""; private var clipboardListener:ClipboardManager.OnPrimaryClipChangedListener?=null
    override fun onCreate(){super.onCreate();instance=this;val cm=getSystemService(CLIPBOARD_SERVICE) as ClipboardManager;clipboardListener=ClipboardManager.OnPrimaryClipChangedListener{PhormiKeyboardClipboardStore.capturePrimaryClipboard(this)};cm.addPrimaryClipChangedListener(clipboardListener)}
    override fun onDestroy(){stopVoice();val cm=getSystemService(CLIPBOARD_SERVICE) as ClipboardManager;clipboardListener?.let(cm::removePrimaryClipChangedListener);clipboardListener=null;if(instance===this)instance=null;super.onDestroy()}
    override fun onStartInput(a:EditorInfo?,restarting:Boolean){super.onStartInput(a,restarting);editorInfo=a;selectionStart=0;selectionEnd=0;panel=Panel.KEYBOARD;capsLock=false;shift=PhormiKeyboardPreferences.autoCaps(this)}
    override fun onStartInputView(info:EditorInfo?,restarting:Boolean){super.onStartInputView(info,restarting);editorInfo=info?:editorInfo;PhormiKeyboardClipboardStore.capturePrimaryClipboard(this);panel=Panel.KEYBOARD;setInputView(render())}
    override fun onFinishInput(){stopVoice();editorInfo=null;super.onFinishInput()}
    override fun onUpdateSelection(a:Int,b:Int,c:Int,d:Int,e:Int,f:Int){super.onUpdateSelection(a,b,c,d,e,f);selectionStart=c;selectionEnd=d}
    override fun onEvaluateFullscreenMode()=false
    override fun onCreateInputView():View=render()
    override fun onStartCommand(intent:Intent?,flags:Int,startId:Int):Int{if(intent?.action==ACTION_COMMIT_TEXT)intent.getStringExtra(EXTRA_TEXT)?.let(::commitText);return START_NOT_STICKY}
    private fun render():View=when(panel){Panel.KEYBOARD->buildKeyboard();Panel.NUMBERS->buildNumbers();Panel.SYMBOLS->buildSymbols();Panel.EMOJI->buildEmoji();Panel.CLIPBOARD->buildClipboard();Panel.GIF->buildMediaPanel("GIF");Panel.STICKER->buildMediaPanel("Stickers")}
    private fun root():LinearLayout=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(4,4,4,4);setBackgroundColor(themeColor());isFocusable=true}
    private fun themeColor():Int=when(PhormiKeyboardPreferences.theme(this)){"light"->Color.rgb(235,238,245);"purple"->Color.rgb(42,28,74);"red"->Color.rgb(58,22,28);"blue"->Color.rgb(16,38,64);"green"->Color.rgb(20,55,40);"gold"->Color.rgb(62,50,18);else->Color.rgb(13,20,34)}
    private fun textColor():Int=if(PhormiKeyboardPreferences.theme(this)=="light")Color.rgb(20,25,35)else Color.WHITE
    private fun suggestionStrip(root:LinearLayout){val row=HorizontalScrollView(this).apply{isHorizontalScrollBarEnabled=false};val inner=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL};val before=currentInputConnection?.getTextBeforeCursor(180,0)?.toString().orEmpty();suggestWords(before).forEach{key(inner,it){replaceCurrentWord(it)}};if(PhormiKeyboardPreferences.aiEmoji(this)){PhormiContextEmojiEngine.expressive(before).forEach{key(inner,it){commitText(it)}};if(before.trim().length>=6&&PhormiKeyboardPreferences.pollinationsKey(this).isNotBlank()&&before!=lastContext){lastContext=before;val token=++aiJobToken;PhormiContextEmojiEngine.generate(this,before){file->if(token==aiJobToken&&file!=null&&panel==Panel.KEYBOARD)addAiImage(inner,file)}}};if(inner.childCount==0)key(inner,"✨ AI emoji"){startAiEmojiStudio()};key(inner,"😀"){panel=Panel.EMOJI;setInputView(render())};key(inner,"📋"){panel=Panel.CLIPBOARD;setInputView(render())};key(inner,"GIF"){panel=Panel.GIF;setInputView(render())};key(inner,"Stickers"){panel=Panel.STICKER;setInputView(render())};key(inner,"⚙"){startActivity(Intent(this,PhormiKeyboardSettingsActivity::class.java).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK))};row.addView(inner,LinearLayout.LayoutParams(-2,-1));root.addView(row,LinearLayout.LayoutParams(-1,46))}
    private fun addAiImage(row:LinearLayout,file:java.io.File){val image=ImageButton(this).apply{setImageBitmap(BitmapFactory.decodeFile(file.absolutePath));background=ColorDrawable(Color.TRANSPARENT);scaleType=ImageView.ScaleType.CENTER_INSIDE;contentDescription="AI emoji";setOnClickListener{commitContent(PhormiKeyboardStickerStore.contentUri(this@PhormiKeyboardService,file))}};row.addView(image,LinearLayout.LayoutParams(54,46))}
    private fun buildKeyboard():View{val r=root();suggestionStrip(r);listOf("qwertyuiop","asdfghjkl","zxcvbnm").forEach{r.addView(letterRow(it),LinearLayout.LayoutParams(-1,0,1f))};r.addView(bottomRow(),LinearLayout.LayoutParams(-1,0,1.05f));return r}
    private fun buildNumbers():View{val r=root();suggestionStrip(r);listOf("1234567890","-/:;()$&@\"",".,?!'#+=","%*<>_[]{}~^").forEach{r.addView(charRow(it),LinearLayout.LayoutParams(-1,0,1f))};r.addView(bottomRow(),LinearLayout.LayoutParams(-1,0,1.05f));return r}
    private fun buildSymbols():View{val r=root();suggestionStrip(r);listOf("!@#\$%^&*()","_+-=/:;\"'","<>{}[]\\|~`","©®™§¶•°¿¡±×÷∞≠≈").forEach{r.addView(charRow(it),LinearLayout.LayoutParams(-1,0,1f))};r.addView(symbolBottom(),LinearLayout.LayoutParams(-1,0,1.05f));return r}
    private fun letterRow(chars:String):View{val row=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER};chars.forEach{c->val s=if(shift||capsLock)c.uppercaseChar().toString()else c.toString();key(row,s){commitText(s);if(shift&&!capsLock){shift=false;setInputView(render())}}};return row}
    private fun charRow(chars:String):View{val row=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER};chars.forEach{c->key(row,c.toString()){commitText(c.toString())}};return row}
    private fun bottomRow():View{val row=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER};key(row,"⇧"){if(capsLock){capsLock=false;shift=false}else if(shift){capsLock=true;shift=false}else shift=true;setInputView(render())};key(row,"123"){panel=Panel.NUMBERS;setInputView(render())};key(row,"Space",3.2f){commitSpace()};key(row,"←"){moveCursor(-1)};key(row,"→"){moveCursor(1)};key(row,"⌫"){deleteBackward()};key(row,"↵"){sendEditorAction()};key(row,if(speechListening)"■" else "🎙"){toggleVoice()};return row}
    private fun symbolBottom():View{val row=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER};key(row,"ABC"){panel=Panel.KEYBOARD;setInputView(render())};key(row,"123"){panel=Panel.NUMBERS;setInputView(render())};key(row,"Space",3.2f){commitSpace()};key(row,"←"){moveCursor(-1)};key(row,"→"){moveCursor(1)};key(row,"⌫"){deleteBackward()};key(row,"↵"){sendEditorAction()};return row}
    private fun buildEmoji():View{val r=root();val nav=HorizontalScrollView(this).apply{isHorizontalScrollBarEnabled=false};val cats=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};PhormiKeyboardEmoji.categories.keys.forEachIndexed{i,icon->key(cats,icon){emojiCategory=i;setInputView(render())}};key(cats,"ABC"){panel=Panel.KEYBOARD;setInputView(render())};nav.addView(cats);r.addView(nav,LinearLayout.LayoutParams(-1,44));val actions=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};key(actions,"✨ AI"){startAiEmojiStudio()};key(actions,"📋"){panel=Panel.CLIPBOARD;setInputView(render())};key(actions,"GIF"){panel=Panel.GIF;setInputView(render())};key(actions,"Stickers"){panel=Panel.STICKER;setInputView(render())};r.addView(actions,LinearLayout.LayoutParams(-1,44));val scroll=ScrollView(this);val grid=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};PhormiKeyboardEmoji.categories.values.elementAtOrNull(emojiCategory).orEmpty().chunked(8).forEach{group->val rr=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};group.forEach{e->key(rr,e){commitText(e)}};grid.addView(rr,LinearLayout.LayoutParams(-1,0,1f))};scroll.addView(grid);r.addView(scroll,LinearLayout.LayoutParams(-1,0,1f));return r}
    private fun buildClipboard():View{val r=root();val head=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};key(head,"← Keyboard"){panel=Panel.KEYBOARD;setInputView(render())};key(head,"Clear"){PhormiKeyboardClipboardStore.clearUnpinned(this);setInputView(render())};r.addView(head,LinearLayout.LayoutParams(-1,44));val scroll=ScrollView(this);val list=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val items=PhormiKeyboardClipboardStore.list(this);if(items.isEmpty())list.addView(TextView(this).apply{text="Copy text normally while Phormi is active and it will appear here.";setTextColor(textColor());setPadding(12,20,12,20)});items.forEach{item->val rr=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};val tv=TextView(this).apply{text=item.text;setTextColor(textColor());textSize=13f;maxLines=3;setPadding(10,8,4,8)};rr.addView(tv,LinearLayout.LayoutParams(0,-2,1f));key(rr,if(item.pinned)"📌" else "○"){PhormiKeyboardClipboardStore.togglePinned(this@PhormiKeyboardService,item.text);setInputView(render())};rr.setOnClickListener{commitText(item.text)};list.addView(rr)};scroll.addView(list);r.addView(scroll,LinearLayout.LayoutParams(-1,0,1f));return r}
    private fun buildMediaPanel(title:String):View{val r=root();val head=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};key(head,"← Keyboard"){panel=Panel.KEYBOARD;setInputView(render())};key(head,"Import"){openMediaPicker(if(title=="GIF")"gif" else "sticker")};r.addView(TextView(this).apply{text=title;setTextColor(textColor());textSize=17f;setPadding(12,8,8,8)});r.addView(head,LinearLayout.LayoutParams(-1,48));val scroll=ScrollView(this);val body=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};if(title=="Stickers"){PhormiKeyboardStickerPackStore.packs(this).forEach{pack->body.addView(TextView(this@PhormiKeyboardService).apply{text="📦 ${pack.name} (${pack.files.size})";setTextColor(textColor());setPadding(12,14,12,14);setOnClickListener{PhormiKeyboardStickerPackStore.files(this@PhormiKeyboardService,pack).firstOrNull()?.let{f->commitContent(PhormiKeyboardStickerStore.contentUri(this@PhormiKeyboardService,f))}}})}}else body.addView(TextView(this).apply{text="Import a GIF to use it here. Android will insert it through the active editor when that editor accepts image content.";setTextColor(textColor());setPadding(12,18,12,18)});scroll.addView(body);r.addView(scroll,LinearLayout.LayoutParams(-1,0,1f));return r}
    private fun openMediaPicker(mode:String){startActivity(Intent(this,PhormiKeyboardMediaActivity::class.java).putExtra(PhormiKeyboardMediaActivity.EXTRA_MODE,mode).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK))}
    private fun startAiEmojiStudio(){startActivity(Intent(this,PhormiAiEmojiActivity::class.java).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK))}
    private fun key(row:LinearLayout,label:String,weight:Float=1f,action:()->Unit):Button=Button(this).apply{text=label;minWidth=0;minHeight=0;setPadding(1,0,1,0);isAllCaps=false;setTextColor(textColor());contentDescription=label;setOnClickListener{action()};row.addView(this,LinearLayout.LayoutParams(0,-1,weight).apply{setMargins(2,2,2,2)})}
    private fun suggestWords(text:String):List<String>{if(!PhormiKeyboardPreferences.suggestions(this)||isPasswordField())return emptyList();val token=text.takeLastWhile{!it.isWhitespace()}.lowercase();if(token.isEmpty())return emptyList();val words=COMMON_WORDS.filter{it.startsWith(token)&&it!=token}.take(5);return if(words.isEmpty()&&token.length>1)listOf(PhormiGlideEngine.resolve(token)).filter{it!=token}.take(2)else words}
    private fun replaceCurrentWord(word:String){val ic=currentInputConnection?:return;val before=ic.getTextBeforeCursor(200,0)?.toString().orEmpty();val token=before.takeLastWhile{!it.isWhitespace()};if(token.isNotEmpty())ic.deleteSurroundingText(token.length,0);commitText(word)}
    private fun commitText(text:String){currentInputConnection?.let{runCatching{it.commitText(text,1)}}}
    private fun commitSpace(){val ic=currentInputConnection?:return;runCatching{correctCompletedWord(ic);ic.commitText(" ",1);if(PhormiKeyboardPreferences.autoCaps(this)){val after=ic.getTextBeforeCursor(3,0)?.toString().orEmpty();if(after.endsWith(". ")||after.endsWith("! ")||after.endsWith("? ")||after.endsWith("\n"))shift=true};setInputView(render())}}
    private fun correctCompletedWord(ic:InputConnection){if(!PhormiKeyboardPreferences.autocorrect(this))return;val before=ic.getTextBeforeCursor(80,0)?.toString().orEmpty();val word=before.takeLastWhile{!it.isWhitespace()};if(word.isBlank())return;val right=CORRECTIONS[word.lowercase()]?:return;val replacement=if(word.first().isUpperCase())right.replaceFirstChar{it.uppercase()}else right;ic.deleteSurroundingText(word.length,0);ic.commitText(replacement,1)}
    private fun deleteBackward(){val ic=currentInputConnection?:return;runCatching{if(!ic.getSelectedText(0).isNullOrEmpty()){ic.commitText("",1);return};if(Build.VERSION.SDK_INT>=24)ic.deleteSurroundingTextInCodePoints(1,0)else ic.deleteSurroundingText(1,0)}}
    private fun moveCursor(delta:Int){val ic=currentInputConnection?:return;runCatching{if(selectionStart!=selectionEnd){val c=if(delta<0)min(selectionStart,selectionEnd)else max(selectionStart,selectionEnd);ic.setSelection(c,c);selectionStart=c;selectionEnd=c;return};val target=(selectionStart+delta).coerceAtLeast(0);if(ic.setSelection(target,target)){selectionStart=target;selectionEnd=target}}}
    private fun sendEditorAction(){val ic=currentInputConnection?:return;val a=(editorInfo?.imeOptions?:0) and EditorInfo.IME_MASK_ACTION;runCatching{if(a!=EditorInfo.IME_ACTION_NONE&&a!=EditorInfo.IME_ACTION_UNSPECIFIED){if(!ic.performEditorAction(a))ic.sendKeyEvent(KeyEvent(KeyEvent.ACTION_DOWN,KeyEvent.KEYCODE_ENTER))}else{ic.sendKeyEvent(KeyEvent(KeyEvent.ACTION_DOWN,KeyEvent.KEYCODE_ENTER));ic.sendKeyEvent(KeyEvent(KeyEvent.ACTION_UP,KeyEvent.KEYCODE_ENTER))}}}
    private fun isPasswordField():Boolean{val v=(editorInfo?.inputType?:0) and InputType.TYPE_MASK_VARIATION;return v==InputType.TYPE_TEXT_VARIATION_PASSWORD||v==InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD||v==InputType.TYPE_TEXT_VARIATION_WEB_PASSWORD}
    private fun toggleVoice(){if(speechListening)stopVoice()else startVoice()}
    private fun startVoice(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){Toast.makeText(this,"Grant microphone permission in Phormi Keyboard settings first",Toast.LENGTH_SHORT).show();return};if(!SpeechRecognizer.isRecognitionAvailable(this)){Toast.makeText(this,"No speech recognition service is available",Toast.LENGTH_SHORT).show();return};stopVoice();speech=SpeechRecognizer.createSpeechRecognizer(this).apply{setRecognitionListener(object:RecognitionListener{override fun onReadyForSpeech(p:Bundle?){speechListening=true;setInputView(render())};override fun onBeginningOfSpeech(){};override fun onRmsChanged(v:Float){};override fun onBufferReceived(b:ByteArray?){};override fun onEndOfSpeech(){speechListening=false;setInputView(render())};override fun onError(e:Int){speechListening=false;setInputView(render());if(e!=SpeechRecognizer.ERROR_NO_MATCH)Toast.makeText(this@PhormiKeyboardService,"Voice input error: $e",Toast.LENGTH_SHORT).show()};override fun onResults(r:Bundle?){r?.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION)?.firstOrNull()?.takeIf{it.isNotBlank()}?.let{commitText(it+" ")};speechListening=false;setInputView(render())};override fun onPartialResults(r:Bundle?){};override fun onEvent(t:Int,p:Bundle?){} })};val i=Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH).apply{putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);putExtra(RecognizerIntent.EXTRA_LANGUAGE,Locale.getDefault().toLanguageTag());putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS,true)};runCatching{speech?.startListening(i)}.onFailure{stopVoice()}}
    private fun stopVoice(){speechListening=false;runCatching{speech?.stopListening()};runCatching{speech?.destroy()};speech=null}
    private fun commitContent(uri:Uri):Boolean{val ic=currentInputConnection?:return false;if(Build.VERSION.SDK_INT<25)return false;val requested=editorInfo?.contentMimeTypes?.toList().orEmpty();val mime=when{requested.any{it=="image/gif"}->"image/gif";requested.any{it.startsWith("image/")}->"image/png";else->"image/*"};if(requested.isEmpty()||requested.any{ClipDescription.compareMimeTypes(mime,it)}){val info=InputContentInfo(uri,ClipDescription("Phormi media",arrayOf(mime)),null);if(runCatching{ic.commitContent(info,InputConnection.INPUT_CONTENT_GRANT_READ_URI_PERMISSION,Bundle())}.getOrDefault(false))return true};runCatching{(getSystemService(CLIPBOARD_SERVICE) as ClipboardManager).setPrimaryClip(ClipData.newRawUri("Phormi media",uri))};return false}
    companion object Data { val CORRECTIONS=mapOf("teh" to "the","adn" to "and","taht" to "that","thier" to "their","recieve" to "receive","recieved" to "received","becuase" to "because","definately" to "definitely","seperate" to "separate","occured" to "occurred","untill" to "until","wich" to "which","waht" to "what","dont" to "don't","cant" to "can't","wont" to "won't","im" to "I'm","ive" to "I've","id" to "I'd","ill" to "I'll","doesnt" to "doesn't","isnt" to "isn't","wasnt" to "wasn't","didnt" to "didn't","couldnt" to "couldn't","shouldnt" to "shouldn't","wouldnt" to "wouldn't","alot" to "a lot","thats" to "that's","ur" to "your"); val COMMON_WORDS="the and that this there their they them then than you your yours you're are was were with what when where why how have has had for from not now can could should would will just very really like love want need know think make going come good great about into out over under after before because please thanks hello hey yes yeah okay today tomorrow later home work friend family message send open close search download share keyboard browser emoji sticker settings phone text time day night morning money school student project happy sad angry amazing awesome cool nice sorry welcome congratulations maybe more much some any all one two three".split(" ").toSet() }
}
