package com.uong.phormi

import android.Manifest
import android.content.*
import android.content.pm.PackageManager
import android.content.res.ColorStateList
import android.graphics.*
import android.graphics.drawable.*
import android.inputmethodservice.InputMethodService
import android.net.Uri
import android.os.*
import android.speech.*
import android.text.InputType
import android.view.*
import android.view.inputmethod.*
import android.widget.*
import java.util.Locale
import kotlin.math.max
import kotlin.math.min

class PhormiKeyboardService : InputMethodService() {
    companion object { const val ACTION_COMMIT_TEXT="com.uong.phormi.keyboard.COMMIT_TEXT"; const val EXTRA_TEXT="text"; private var instance:PhormiKeyboardService?=null; fun commitPickedContent(context:Context,uri:Uri):Boolean=instance?.commitContent(uri)?:false }
    private enum class Panel { KEYBOARD, NUMBERS, SYMBOLS, EMOJI, CLIPBOARD, TOOLS, GIF, STICKER }
    private var shift=false; private var capsLock=false; private var panel=Panel.KEYBOARD; private var emojiCategory=0; private var editorInfo:EditorInfo?=null; private var selectionStart=0; private var selectionEnd=0; private var speech:SpeechRecognizer?=null; private var speechListening=false; private var aiToken=0; private var lastAiContext=""; private var clipListener:ClipboardManager.OnPrimaryClipChangedListener?=null
    private val corrections=mapOf("teh" to "the","adn" to "and","taht" to "that","thier" to "their","recieve" to "receive","recieved" to "received","becuase" to "because","definately" to "definitely","seperate" to "separate","occured" to "occurred","untill" to "until","wich" to "which","waht" to "what","dont" to "don't","cant" to "can't","wont" to "won't","im" to "I'm","ive" to "I've","id" to "I'd","ill" to "I'll","doesnt" to "doesn't","isnt" to "isn't","wasnt" to "wasn't","didnt" to "didn't","couldnt" to "couldn't","shouldnt" to "shouldn't","wouldnt" to "wouldn't","alot" to "a lot","thats" to "that's","ur" to "your")
    private val words="the and that this there their they them then than you your yours you're are was were with what when where why how have has had for from not now can could should would will just very really like love want need know think make going come good great about into out over under after before because please thanks hello hey yes yeah okay today tomorrow later home work friend family message send open close search download share keyboard browser emoji sticker settings phone text time day night morning money school student project happy sad angry amazing awesome cool nice sorry welcome congratulations maybe more much some any all one two three".split(" ").toSet()
    override fun onCreate(){super.onCreate();instance=this;val cm=getSystemService(CLIPBOARD_SERVICE) as ClipboardManager;clipListener=ClipboardManager.OnPrimaryClipChangedListener{PhormiKeyboardClipboardStore.capturePrimaryClipboard(this)};cm.addPrimaryClipChangedListener(clipListener)}
    override fun onDestroy(){stopVoice();val cm=getSystemService(CLIPBOARD_SERVICE) as ClipboardManager;clipListener?.let(cm::removePrimaryClipChangedListener);clipListener=null;if(instance===this)instance=null;super.onDestroy()}
    override fun onStartInput(a:EditorInfo?,restarting:Boolean){super.onStartInput(a,restarting);editorInfo=a;selectionStart=0;selectionEnd=0;panel=Panel.KEYBOARD;capsLock=false;shift=PhormiKeyboardPreferences.autoCaps(this)}
    override fun onStartInputView(info:EditorInfo?,restarting:Boolean){super.onStartInputView(info,restarting);editorInfo=info?:editorInfo;PhormiKeyboardClipboardStore.capturePrimaryClipboard(this);panel=Panel.KEYBOARD;setInputView(render())}
    override fun onFinishInput(){stopVoice();editorInfo=null;super.onFinishInput()}
    override fun onUpdateSelection(a:Int,b:Int,c:Int,d:Int,e:Int,f:Int){super.onUpdateSelection(a,b,c,d,e,f);selectionStart=c;selectionEnd=d}
    override fun onEvaluateFullscreenMode()=false
    override fun onCreateInputView():View=render()
    override fun onStartCommand(i:Intent?,flags:Int,startId:Int):Int{if(i?.action==ACTION_COMMIT_TEXT)i.getStringExtra(EXTRA_TEXT)?.let(::commitText);return START_NOT_STICKY}
    private fun render():View=when(panel){Panel.KEYBOARD->keyboard();Panel.NUMBERS->numbers();Panel.SYMBOLS->symbols();Panel.EMOJI->emoji();Panel.CLIPBOARD->clipboard();Panel.TOOLS->tools();Panel.GIF->media("GIF");Panel.STICKER->media("Stickers")}
    private fun root():LinearLayout=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(4,4,4,4);setBackgroundColor(themeColor());applyWallpaper(this)}
    private fun themeColor():Int=when(PhormiKeyboardPreferences.theme(this)){"light"->Color.rgb(235,238,245);"purple"->Color.rgb(42,28,74);"red"->Color.rgb(58,22,28);"blue"->Color.rgb(16,38,64);"green"->Color.rgb(20,55,40);"gold"->Color.rgb(62,50,18);else->Color.rgb(13,20,34)}
    private fun fg():Int=if(PhormiKeyboardPreferences.theme(this)=="light")Color.rgb(20,25,35)else Color.WHITE
    private fun applyWallpaper(v:View){val s=PhormiKeyboardPreferences.wallpaper(this);if(s.isBlank())return;runCatching{contentResolver.openInputStream(Uri.parse(s))?.use{BitmapFactory.decodeStream(it)}?.let{b->v.background=BitmapDrawable(resources,b).apply{gravity=Gravity.FILL;alpha=90}}}}
    private fun strip(r:LinearLayout){val h=HorizontalScrollView(this).apply{isHorizontalScrollBarEnabled=false};val row=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL};val text=currentInputConnection?.getTextBeforeCursor(180,0)?.toString().orEmpty();suggest(text).forEach{key(row,it){replaceWord(it)}};if(PhormiKeyboardPreferences.aiEmoji(this)){PhormiContextEmojiEngine.expressive(text).forEach{key(row,it){commitText(it)}};if(text.trim().length>=6&&PhormiKeyboardPreferences.pollinationsKey(this).isNotBlank()&&text!=lastAiContext){lastAiContext=text;val t=++aiToken;PhormiContextEmojiEngine.generate(this,text){f->if(t==aiToken&&f!=null&&panel==Panel.KEYBOARD)addAiImage(row,f)}}};if(row.childCount==0)key(row,"✨ AI emoji"){startAiStudio()};key(row,"😀"){panel=Panel.EMOJI;refresh()};key(row,"📋"){panel=Panel.CLIPBOARD;refresh()};key(row,"Tools"){panel=Panel.TOOLS;refresh()};key(row,"GIF"){panel=Panel.GIF;refresh()};key(row,"Stickers"){panel=Panel.STICKER;refresh()};key(row,"⚙"){startActivity(Intent(this,PhormiKeyboardSettingsActivity::class.java).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK))};h.addView(row,LinearLayout.LayoutParams(-2,-1));r.addView(h,LinearLayout.LayoutParams(-1,46))}
    private fun addAiImage(row:LinearLayout,f:java.io.File){val b=ImageButton(this).apply{setImageBitmap(BitmapFactory.decodeFile(f.absolutePath));background=ColorDrawable(Color.TRANSPARENT);contentDescription="AI emoji";scaleType=ImageView.ScaleType.CENTER_INSIDE;setOnClickListener{commitContent(PhormiKeyboardStickerStore.contentUri(this@PhormiKeyboardService,f))}};row.addView(b,LinearLayout.LayoutParams(54,46))}
    private fun keyboard():View{val r=root();strip(r);listOf("qwertyuiop","asdfghjkl","zxcvbnm").forEach{r.addView(letterRow(it),LinearLayout.LayoutParams(-1,0,1f))};r.addView(bottom(),LinearLayout.LayoutParams(-1,0,1.05f));return r}
    private fun numbers():View{val r=root();strip(r);listOf("1234567890","-/:;()$&@\"",".,?!'#+=","%*<>_[]{}~^").forEach{r.addView(chars(it),LinearLayout.LayoutParams(-1,0,1f))};r.addView(bottom(),LinearLayout.LayoutParams(-1,0,1.05f));return r}
    private fun symbols():View{val r=root();strip(r);listOf("!@#\$%^&*()","_+-=/:;\"'","<>{}[]\\|~`","©®™§¶•°¿¡±×÷∞≠≈").forEach{r.addView(chars(it),LinearLayout.LayoutParams(-1,0,1f))};r.addView(symbolBottom(),LinearLayout.LayoutParams(-1,0,1.05f));return r}
    private fun letterRow(s:String):View{val row=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER};s.forEach{c->{val t=if(shift||capsLock)c.uppercaseChar().toString()else c.toString();key(row,t){commitText(t);if(shift&&!capsLock){shift=false;refresh()}}}};return row}
    private fun chars(s:String):View{val row=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER};s.forEach{c->key(row,c.toString()){commitText(c.toString())}};return row}
    private fun bottom():View{val row=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER};val sh=key(row,"⇧"){if(capsLock){capsLock=false;shift=false}else if(shift){capsLock=true;shift=false}else shift=true;refresh()};sh.backgroundTintList=ColorStateList.valueOf(if(capsLock)Color.rgb(210,45,55)else if(shift)Color.WHITE else Color.rgb(45,55,72));sh.setTextColor(if(shift&&!capsLock)Color.rgb(20,25,35)else Color.WHITE);if(panel==Panel.KEYBOARD)key(row,"123"){panel=Panel.NUMBERS;refresh()}else if(panel==Panel.NUMBERS)key(row,"🔣"){panel=Panel.SYMBOLS;refresh()}else key(row,"ABC"){panel=Panel.KEYBOARD;refresh()};key(row,"Space",3.2f){commitSpace()};key(row,"←"){moveCursor(-1)};key(row,"→"){moveCursor(1)};key(row,"⌫"){deleteBackward()};key(row,"↵"){sendEditorAction()};key(row,if(speechListening)"■"else"🎙"){toggleVoice()};return row}
    private fun symbolBottom():View{val row=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER};key(row,"ABC"){panel=Panel.KEYBOARD;refresh()};key(row,"123"){panel=Panel.NUMBERS;refresh()};key(row,"Space",3.2f){commitSpace()};key(row,"←"){moveCursor(-1)};key(row,"→"){moveCursor(1)};key(row,"⌫"){deleteBackward()};key(row,"↵"){sendEditorAction()};return row}
    private fun emoji():View{val r=root();val nav=HorizontalScrollView(this).apply{isHorizontalScrollBarEnabled=false};val cats=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};PhormiKeyboardEmoji.categories.keys.forEachIndexed{i,e->key(cats,e){emojiCategory=i;refresh()}};key(cats,"ABC"){panel=Panel.KEYBOARD;refresh()};nav.addView(cats);r.addView(nav,LinearLayout.LayoutParams(-1,44));val actions=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};key(actions,"✨ AI"){startAiStudio()};key(actions,"📋"){panel=Panel.CLIPBOARD;refresh()};key(actions,"Tools"){panel=Panel.TOOLS;refresh()};key(actions,"GIF"){panel=Panel.GIF;refresh()};key(actions,"Stickers"){panel=Panel.STICKER;refresh()};r.addView(actions,LinearLayout.LayoutParams(-1,44));val scroll=ScrollView(this);val grid=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};PhormiKeyboardEmoji.categories.values.elementAtOrNull(emojiCategory).orEmpty().chunked(8).forEach{g->val rr=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};g.forEach{e->key(rr,e){commitText(e)}};grid.addView(rr,LinearLayout.LayoutParams(-1,0,1f))};scroll.addView(grid);r.addView(scroll,LinearLayout.LayoutParams(-1,0,1f));return r}
    private fun clipboard():View{val r=root();val h=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};key(h,"← Keyboard"){panel=Panel.KEYBOARD;refresh()};key(h,"Clear"){PhormiKeyboardClipboardStore.clearUnpinned(this);refresh()};r.addView(h,LinearLayout.LayoutParams(-1,44));val scroll=ScrollView(this);val list=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val items=PhormiKeyboardClipboardStore.list(this);if(items.isEmpty())list.addView(TextView(this).apply{text="Copy text normally while Phormi is active and it appears here.";setTextColor(fg());setPadding(12,20,12,20)});items.forEach{item->val rr=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};val tv=TextView(this).apply{text=item.text;setTextColor(fg());maxLines=3;setPadding(10,8,4,8)};rr.addView(tv,LinearLayout.LayoutParams(0,-2,1f));key(rr,if(item.pinned)"📌"else"○"){PhormiKeyboardClipboardStore.togglePinned(this@PhormiKeyboardService,item.text);refresh()};rr.setOnClickListener{commitText(item.text)};list.addView(rr)};scroll.addView(list);r.addView(scroll,LinearLayout.LayoutParams(-1,0,1f));return r}
    private fun tools():View{val r=root();key(r,"← Keyboard"){panel=Panel.KEYBOARD;refresh()};val grid=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};listOf("Select all","Copy","Cut","Paste","Clear clipboard").forEach{label->key(grid,label){when(label){"Select all"->selectAll();"Copy"->copy();"Cut"->cut();"Paste"->paste();"Clear clipboard"->PhormiKeyboardClipboardStore.clearUnpinned(this)};if(label!="Clear clipboard")Toast.makeText(this,"$label",Toast.LENGTH_SHORT).show();refresh()}};r.addView(grid,LinearLayout.LayoutParams(-1,0,1f));return r}
    private fun media(title:String):View{val r=root();val h=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};key(h,"← Keyboard"){panel=Panel.KEYBOARD;refresh()};key(h,"Import"){startActivity(Intent(this,PhormiKeyboardMediaActivity::class.java).putExtra(PhormiKeyboardMediaActivity.EXTRA_MODE,if(title=="GIF")"gif"else"sticker").addFlags(Intent.FLAG_ACTIVITY_NEW_TASK))};r.addView(TextView(this).apply{text=title;setTextColor(fg());textSize=17f;setPadding(10,6,6,6)});r.addView(h,LinearLayout.LayoutParams(-1,46));val scroll=ScrollView(this);val body=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};if(title=="Stickers")PhormiKeyboardStickerPackStore.packs(this).forEach{p->body.addView(TextView(this@PhormiKeyboardService).apply{text="📦 ${p.name} (${p.files.size})";setTextColor(fg());setPadding(12,14,12,14);setOnClickListener{PhormiKeyboardStickerPackStore.files(this@PhormiKeyboardService,p).firstOrNull()?.let{f->commitContent(PhormiKeyboardStickerStore.contentUri(this@PhormiKeyboardService,f))}}})}else body.addView(TextView(this).apply{text="GIF import is now a keyboard panel. Choose Import to add a GIF.";setTextColor(fg());setPadding(12,18,12,18)});scroll.addView(body);r.addView(scroll,LinearLayout.LayoutParams(-1,0,1f));return r}
    private fun refresh(){setInputView(render())}
    private fun key(row:LinearLayout,label:String,weight:Float=1f,action:()->Unit):Button=Button(this).apply{text=label;minWidth=0;minHeight=0;setPadding(1,0,1,0);isAllCaps=false;setTextColor(fg());contentDescription=label;setOnClickListener{action()};val gap=((PhormiKeyboardPreferences.keyWidth(this)-100)/12).coerceIn(-2,3)+2;row.addView(this,LinearLayout.LayoutParams(0,-1,weight).apply{setMargins(gap,gap,gap,gap)})}
    private fun suggest(text:String):List<String>{if(!PhormiKeyboardPreferences.suggestions(this)||password())return emptyList();val token=text.takeLastWhile{!it.isWhitespace()}.lowercase();if(token.isEmpty())return emptyList();return words.filter{it.startsWith(token)&&it!=token}.take(5)}
    private fun replaceWord(word:String){val ic=currentInputConnection?:return;val before=ic.getTextBeforeCursor(200,0)?.toString().orEmpty();val token=before.takeLastWhile{!it.isWhitespace()};if(token.isNotEmpty())ic.deleteSurroundingText(token.length,0);commitText(word)}
    private fun commitText(t:String){currentInputConnection?.let{runCatching{it.commitText(t,1)}}}
    private fun commitSpace(){val ic=currentInputConnection?:return;runCatching{if(PhormiKeyboardPreferences.autocorrect(this))correctWord(ic);ic.commitText(" ",1);if(PhormiKeyboardPreferences.autoCaps(this)){val s=ic.getTextBeforeCursor(3,0)?.toString().orEmpty();if(s.endsWith(". ")||s.endsWith("! ")||s.endsWith("? ")||s.endsWith("\n"))shift=true};refresh()}}
    private fun correctWord(ic:InputConnection){val before=ic.getTextBeforeCursor(80,0)?.toString().orEmpty();val w=before.takeLastWhile{!it.isWhitespace()};val r=corrections[w.lowercase()]?:return;ic.deleteSurroundingText(w.length,0);ic.commitText(if(w.first().isUpperCase())r.replaceFirstChar{it.uppercase()}else r,1)}
    private fun deleteBackward(){val ic=currentInputConnection?:return;runCatching{if(!ic.getSelectedText(0).isNullOrEmpty()){ic.commitText("",1);return};if(Build.VERSION.SDK_INT>=24)ic.deleteSurroundingTextInCodePoints(1,0)else ic.deleteSurroundingText(1,0)}}
    private fun moveCursor(d:Int){val ic=currentInputConnection?:return;runCatching{if(selectionStart!=selectionEnd){val c=if(d<0)min(selectionStart,selectionEnd)else max(selectionStart,selectionEnd);ic.setSelection(c,c);selectionStart=c;selectionEnd=c;return};val t=(selectionStart+d).coerceAtLeast(0);if(ic.setSelection(t,t)){selectionStart=t;selectionEnd=t}}}
    private fun sendEditorAction(){val ic=currentInputConnection?:return;val a=(editorInfo?.imeOptions?:0) and EditorInfo.IME_MASK_ACTION;runCatching{if(a!=EditorInfo.IME_ACTION_NONE&&a!=EditorInfo.IME_ACTION_UNSPECIFIED){if(!ic.performEditorAction(a))ic.sendKeyEvent(KeyEvent(KeyEvent.ACTION_DOWN,KeyEvent.KEYCODE_ENTER))}else{ic.sendKeyEvent(KeyEvent(KeyEvent.ACTION_DOWN,KeyEvent.KEYCODE_ENTER));ic.sendKeyEvent(KeyEvent(KeyEvent.ACTION_UP,KeyEvent.KEYCODE_ENTER))}}}
    private fun password():Boolean{val v=(editorInfo?.inputType?:0) and InputType.TYPE_MASK_VARIATION;return v==InputType.TYPE_TEXT_VARIATION_PASSWORD||v==InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD||v==InputType.TYPE_TEXT_VARIATION_WEB_PASSWORD}
    private fun selectAll(){currentInputConnection?.let{runCatching{it.performContextMenuAction(android.R.id.selectAll)}}}
    private fun copy(){currentInputConnection?.let{runCatching{it.performContextMenuAction(android.R.id.copy)};PhormiKeyboardClipboardStore.capturePrimaryClipboard(this)}}
    private fun cut(){currentInputConnection?.let{runCatching{it.performContextMenuAction(android.R.id.cut)};PhormiKeyboardClipboardStore.capturePrimaryClipboard(this)}}
    private fun paste(){currentInputConnection?.let{runCatching{it.performContextMenuAction(android.R.id.paste)}}}
    private fun toggleVoice(){if(speechListening)stopVoice()else startVoice()}
    private fun startVoice(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){Toast.makeText(this,"Grant microphone permission in Phormi Keyboard settings first",Toast.LENGTH_SHORT).show();return};if(!SpeechRecognizer.isRecognitionAvailable(this)){Toast.makeText(this,"No speech recognition service is available",Toast.LENGTH_SHORT).show();return};stopVoice();speech=SpeechRecognizer.createSpeechRecognizer(this).apply{setRecognitionListener(object:RecognitionListener{override fun onReadyForSpeech(p:Bundle?){speechListening=true;refresh()};override fun onBeginningOfSpeech(){};override fun onRmsChanged(v:Float){};override fun onBufferReceived(b:ByteArray?){};override fun onEndOfSpeech(){speechListening=false;refresh()};override fun onError(e:Int){speechListening=false;refresh();if(e!=SpeechRecognizer.ERROR_NO_MATCH)Toast.makeText(this@PhormiKeyboardService,"Voice input error: $e",Toast.LENGTH_SHORT).show()};override fun onResults(r:Bundle?){r?.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION)?.firstOrNull()?.takeIf{it.isNotBlank()}?.let{commitText(it+" ")};speechListening=false;refresh()};override fun onPartialResults(r:Bundle?){};override fun onEvent(t:Int,p:Bundle?){} })};val i=Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH).apply{putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);putExtra(RecognizerIntent.EXTRA_LANGUAGE,Locale.getDefault().toLanguageTag());putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS,true)};runCatching{speech?.startListening(i)}.onFailure{stopVoice()}}
    private fun stopVoice(){speechListening=false;runCatching{speech?.stopListening()};runCatching{speech?.destroy()};speech=null}
    private fun startAiStudio(){startActivity(Intent(this,PhormiAiEmojiActivity::class.java).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK))}
    private fun commitContent(uri:Uri):Boolean{val ic=currentInputConnection?:return false;if(Build.VERSION.SDK_INT<25)return false;val requested=editorInfo?.contentMimeTypes?.toList().orEmpty();val mime=when{requested.any{it=="image/gif"}->"image/gif";requested.any{it.startsWith("image/")}->"image/png";else->"image/*"};if(requested.isEmpty()||requested.any{ClipDescription.compareMimeTypes(mime,it)}){val info=InputContentInfo(uri,ClipDescription("Phormi media",arrayOf(mime)),null);if(runCatching{ic.commitContent(info,InputConnection.INPUT_CONTENT_GRANT_READ_URI_PERMISSION,Bundle())}.getOrDefault(false))return true};return false}
}
